twitter = {
    'ACCESS_SECRET': "INSERT YOUR INFO HERE",
    'ACCESS_TOKEN': "INSERT YOUR INFO HERE",
    'CONSUMER_KEY': "INSERT YOUR INFO HERE",
    'CONSUMER_SECRET': "INSERT YOUR INFO HERE"
}

database = {
    'HOST': "INSERT YOUR INFO HERE",
    'PORT': "INSERT YOUR INFO HERE",
    'DB_USERNAME': "INSERT YOUR INFO HERE",
    'DB_PASSWORD': "INSERT YOUR INFO HERE",
    'DATABASE': "INSERT YOUR INFO HERE"
}
